In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model, model_selection
from sklearn.metrics import mean_squared_error, r2_score

In [55]:
X, y = datasets.load_linnerud(return_X_y=True)
X

array([[  5., 162.,  60.],
       [  2., 110.,  60.],
       [ 12., 101., 101.],
       [ 12., 105.,  37.],
       [ 13., 155.,  58.],
       [  4., 101.,  42.],
       [  8., 101.,  38.],
       [  6., 125.,  40.],
       [ 15., 200.,  40.],
       [ 17., 251., 250.],
       [ 17., 120.,  38.],
       [ 13., 210., 115.],
       [ 14., 215., 105.],
       [  1.,  50.,  50.],
       [  6.,  70.,  31.],
       [ 12., 210., 120.],
       [  4.,  60.,  25.],
       [ 11., 230.,  80.],
       [ 15., 225.,  73.],
       [  2., 110.,  43.]])

In [56]:
y

array([[191.,  36.,  50.],
       [189.,  37.,  52.],
       [193.,  38.,  58.],
       [162.,  35.,  62.],
       [189.,  35.,  46.],
       [182.,  36.,  56.],
       [211.,  38.,  56.],
       [167.,  34.,  60.],
       [176.,  31.,  74.],
       [154.,  33.,  56.],
       [169.,  34.,  50.],
       [166.,  33.,  52.],
       [154.,  34.,  64.],
       [247.,  46.,  50.],
       [193.,  36.,  46.],
       [202.,  37.,  62.],
       [176.,  37.,  54.],
       [157.,  32.,  52.],
       [156.,  33.,  54.],
       [138.,  33.,  68.]])

In [57]:
X, y = datasets.load_linnerud(return_X_y=True)


In [58]:
X = X[:, np.newaxis,2]

In [59]:
X[:5]

array([[ 60.],
       [ 60.],
       [101.],
       [ 37.],
       [ 58.]])

In [60]:
y[:5]

array([[191.,  36.,  50.],
       [189.,  37.,  52.],
       [193.,  38.,  58.],
       [162.,  35.,  62.],
       [189.,  35.,  46.]])

In [61]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.33)

In [62]:
X_train[:5]

array([[ 60.],
       [ 50.],
       [ 37.],
       [250.],
       [105.]])

In [63]:
regr = linear_model.LinearRegression()

In [64]:
regr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [65]:
y_pred = regr.predict(X_test)

In [66]:
mean_squared_error(y_test, y_pred)

133.34186352013728

In [67]:
r2_score(y_test, y_pred)

-0.40831202204820616

In [68]:
print("Coefficients: \n", regr.coef_)

Coefficients: 
 [[-0.1853178 ]
 [-0.01791353]
 [-0.0065531 ]]


In [69]:
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))

Mean squared error: 133.34


In [70]:
print("Coefficient of determination: %.2f" % r2_score(y_test, y_pred))

Coefficient of determination: -0.41
